// This file is auto-generated by @hey-api/openapi-ts

export const AdsAccountPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        customer_id: {
            type: 'string',
            title: 'Customer Id'
        },
        descriptive_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Descriptive Name'
        },
        currency_code: {
            type: 'string',
            title: 'Currency Code'
        },
        linked_at: {
            type: 'string',
            title: 'Linked At'
        },
        last_sync_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Sync At'
        },
        sync_status: {
            type: 'string',
            title: 'Sync Status'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'customer_id', 'descriptive_name', 'currency_code', 'linked_at', 'last_sync_at', 'sync_status'],
    title: 'AdsAccountPublic',
    description: 'Public response model for ads account.'
} as const;

export const AnchorRowSchema = {
    properties: {
        anchor_text: {
            type: 'string',
            title: 'Anchor Text'
        },
        backlinks: {
            type: 'integer',
            title: 'Backlinks'
        },
        ref_domains: {
            type: 'integer',
            title: 'Ref Domains'
        }
    },
    type: 'object',
    required: ['anchor_text', 'backlinks', 'ref_domains'],
    title: 'AnchorRow',
    description: 'API response row for anchor texts list.'
} as const;

export const AnchorsResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AnchorRow'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'AnchorsResponse',
    description: 'API response for anchor texts endpoint.'
} as const;

export const AuditIssuePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        audit_run_id: {
            type: 'string',
            format: 'uuid',
            title: 'Audit Run Id'
        },
        page_url: {
            type: 'string',
            title: 'Page Url'
        },
        issue_type: {
            '$ref': '#/components/schemas/IssueType'
        },
        severity: {
            '$ref': '#/components/schemas/IssueSeverity'
        },
        details: {
            additionalProperties: true,
            type: 'object',
            title: 'Details'
        },
        first_seen_run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Seen Run Id'
        },
        is_new: {
            type: 'boolean',
            title: 'Is New'
        }
    },
    type: 'object',
    required: ['id', 'audit_run_id', 'page_url', 'issue_type', 'severity', 'details', 'first_seen_run_id', 'is_new'],
    title: 'AuditIssuePublic'
} as const;

export const AuditIssuesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AuditIssuePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AuditIssuesPublic'
} as const;

export const AuditRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        status: {
            '$ref': '#/components/schemas/AuditStatus'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config'
        },
        stats: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stats'
        },
        progress_pct: {
            type: 'number',
            title: 'Progress Pct'
        },
        progress_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress Message'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'status', 'config', 'stats', 'progress_pct', 'progress_message', 'started_at', 'finished_at', 'error_message', 'created_at'],
    title: 'AuditRunPublic'
} as const;

export const AuditRunsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AuditRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AuditRunsPublic'
} as const;

export const AuditStatusSchema = {
    type: 'string',
    enum: ['queued', 'crawling', 'rendering', 'analyzing', 'diffing', 'completed', 'failed'],
    title: 'AuditStatus'
} as const;

export const BackfillTaskResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        task_id: {
            type: 'string',
            title: 'Task Id'
        },
        days: {
            type: 'integer',
            title: 'Days'
        }
    },
    type: 'object',
    required: ['message', 'task_id', 'days'],
    title: 'BackfillTaskResponse',
    description: 'Response model for backfill task.'
} as const;

export const BacklinkRowSchema = {
    properties: {
        source_url: {
            type: 'string',
            title: 'Source Url'
        },
        target_url: {
            type: 'string',
            title: 'Target Url'
        },
        source_domain: {
            type: 'string',
            title: 'Source Domain'
        },
        anchor_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Anchor Text'
        },
        is_nofollow: {
            type: 'boolean',
            title: 'Is Nofollow'
        },
        first_seen: {
            type: 'string',
            format: 'date-time',
            title: 'First Seen'
        },
        last_seen: {
            type: 'string',
            format: 'date-time',
            title: 'Last Seen'
        }
    },
    type: 'object',
    required: ['source_url', 'target_url', 'source_domain', 'anchor_text', 'is_nofollow', 'first_seen', 'last_seen'],
    title: 'BacklinkRow',
    description: 'API response row for backlinks list.'
} as const;

export const BacklinksResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BacklinkRow'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'BacklinksResponse',
    description: 'API response for backlinks endpoint.'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CSVImportRequestSchema = {
    properties: {
        csv_data: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Csv Data'
        }
    },
    type: 'object',
    required: ['csv_data'],
    title: 'CSVImportRequest',
    description: 'Request model for CSV import.'
} as const;

export const CSVImportResponseSchema = {
    properties: {
        imported: {
            type: 'integer',
            title: 'Imported'
        }
    },
    type: 'object',
    required: ['imported'],
    title: 'CSVImportResponse',
    description: 'Response model for CSV import.'
} as const;

export const CampaignRowSchema = {
    properties: {
        campaign_id: {
            type: 'string',
            title: 'Campaign Id'
        },
        campaign_name: {
            type: 'string',
            title: 'Campaign Name'
        },
        campaign_status: {
            type: 'string',
            title: 'Campaign Status'
        },
        impressions: {
            type: 'integer',
            title: 'Impressions'
        },
        clicks: {
            type: 'integer',
            title: 'Clicks'
        },
        cost_micros: {
            type: 'integer',
            title: 'Cost Micros'
        },
        conversions: {
            type: 'number',
            title: 'Conversions'
        },
        conversion_value: {
            type: 'number',
            title: 'Conversion Value'
        }
    },
    type: 'object',
    required: ['campaign_id', 'campaign_name', 'campaign_status', 'impressions', 'clicks', 'cost_micros', 'conversions', 'conversion_value'],
    title: 'CampaignRow',
    description: 'API response row for campaign performance.'
} as const;

export const CampaignsResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CampaignRow'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'CampaignsResponse',
    description: 'API response for campaigns endpoint.'
} as const;

export const ClusterDetailPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        algorithm: {
            type: 'string',
            title: 'Algorithm'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        total_clicks: {
            type: 'integer',
            title: 'Total Clicks'
        },
        total_impressions: {
            type: 'integer',
            title: 'Total Impressions'
        },
        avg_position: {
            type: 'number',
            title: 'Avg Position'
        },
        query_count: {
            type: 'integer',
            title: 'Query Count'
        },
        members: {
            items: {
                '$ref': '#/components/schemas/ClusterMemberPublic'
            },
            type: 'array',
            title: 'Members'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'label', 'algorithm', 'created_at', 'total_clicks', 'total_impressions', 'avg_position', 'query_count', 'members'],
    title: 'ClusterDetailPublic',
    description: 'Public schema for cluster details with member queries.'
} as const;

export const ClusterMemberPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        cluster_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cluster Id'
        },
        query: {
            type: 'string',
            title: 'Query'
        },
        weight: {
            type: 'number',
            title: 'Weight'
        },
        clicks: {
            type: 'integer',
            title: 'Clicks'
        },
        impressions: {
            type: 'integer',
            title: 'Impressions'
        },
        ctr: {
            type: 'number',
            title: 'Ctr'
        },
        position: {
            type: 'number',
            title: 'Position'
        }
    },
    type: 'object',
    required: ['id', 'cluster_id', 'query', 'weight', 'clicks', 'impressions', 'ctr', 'position'],
    title: 'ClusterMemberPublic',
    description: 'Public schema for a cluster member query with metrics.'
} as const;

export const ClusterPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        algorithm: {
            type: 'string',
            title: 'Algorithm'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        total_clicks: {
            type: 'integer',
            title: 'Total Clicks'
        },
        total_impressions: {
            type: 'integer',
            title: 'Total Impressions'
        },
        avg_position: {
            type: 'number',
            title: 'Avg Position'
        },
        query_count: {
            type: 'integer',
            title: 'Query Count'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'label', 'algorithm', 'created_at', 'total_clicks', 'total_impressions', 'avg_position', 'query_count'],
    title: 'ClusterPublic',
    description: 'Public schema for returning keyword cluster data.'
} as const;

export const ClustersResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClusterPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClustersResponse',
    description: 'Response model for keyword clusters.'
} as const;

export const CrawledPagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        audit_run_id: {
            type: 'string',
            format: 'uuid',
            title: 'Audit Run Id'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        final_url: {
            type: 'string',
            title: 'Final Url'
        },
        depth: {
            type: 'integer',
            title: 'Depth'
        },
        status_code: {
            type: 'integer',
            title: 'Status Code'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        response_time_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Response Time Ms'
        },
        redirect_chain: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Redirect Chain'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        meta_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Meta Description'
        },
        canonical: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Canonical'
        },
        h1_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'H1 Count'
        },
        first_h1: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First H1'
        },
        word_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Word Count'
        },
        meta_robots: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Meta Robots'
        },
        is_rendered: {
            type: 'boolean',
            title: 'Is Rendered'
        },
        rendered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rendered At'
        },
        rendered_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rendered Title'
        },
        rendered_meta_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rendered Meta Description'
        },
        rendered_h1_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rendered H1 Count'
        },
        rendered_word_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rendered Word Count'
        },
        content_hash: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Hash'
        },
        crawled_at: {
            type: 'string',
            format: 'date-time',
            title: 'Crawled At'
        }
    },
    type: 'object',
    required: ['id', 'audit_run_id', 'url', 'final_url', 'depth', 'status_code', 'content_type', 'response_time_ms', 'redirect_chain', 'title', 'meta_description', 'canonical', 'h1_count', 'first_h1', 'word_count', 'meta_robots', 'is_rendered', 'rendered_at', 'rendered_title', 'rendered_meta_description', 'rendered_h1_count', 'rendered_word_count', 'content_hash', 'crawled_at'],
    title: 'CrawledPagePublic'
} as const;

export const CrawledPagesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CrawledPagePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CrawledPagesPublic'
} as const;

export const DeviceTypeSchema = {
    type: 'string',
    enum: ['desktop', 'mobile', 'tablet'],
    title: 'DeviceType',
    description: 'Device types for SERP tracking.'
} as const;

export const GSCPageRowSchema = {
    properties: {
        page: {
            type: 'string',
            title: 'Page'
        },
        clicks: {
            type: 'integer',
            title: 'Clicks'
        },
        impressions: {
            type: 'integer',
            title: 'Impressions'
        },
        ctr: {
            type: 'number',
            title: 'Ctr'
        },
        position: {
            type: 'number',
            title: 'Position'
        }
    },
    type: 'object',
    required: ['page', 'clicks', 'impressions', 'ctr', 'position'],
    title: 'GSCPageRow',
    description: 'Schema for a single page row in GSC API responses.'
} as const;

export const GSCPagesResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GSCPageRow'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GSCPagesResponse',
    description: 'Schema for returning multiple GSC pages.'
} as const;

export const GSCPropertyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        site_url: {
            type: 'string',
            title: 'Site Url'
        },
        permission_level: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Permission Level'
        },
        verified: {
            type: 'boolean',
            title: 'Verified'
        },
        linked_at: {
            type: 'string',
            format: 'date-time',
            title: 'Linked At'
        },
        last_sync_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Sync At'
        },
        sync_status: {
            type: 'string',
            title: 'Sync Status'
        },
        sync_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sync Error'
        },
        search_type: {
            type: 'string',
            title: 'Search Type'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'site_url', 'permission_level', 'verified', 'linked_at', 'last_sync_at', 'sync_status', 'sync_error', 'search_type'],
    title: 'GSCPropertyPublic',
    description: 'Public schema for returning GSC property data.'
} as const;

export const GSCQueriesResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GSCQueryRow'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GSCQueriesResponse',
    description: 'Schema for returning multiple GSC queries.'
} as const;

export const GSCQueryRowSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        clicks: {
            type: 'integer',
            title: 'Clicks'
        },
        impressions: {
            type: 'integer',
            title: 'Impressions'
        },
        ctr: {
            type: 'number',
            title: 'Ctr'
        },
        position: {
            type: 'number',
            title: 'Position'
        }
    },
    type: 'object',
    required: ['query', 'clicks', 'impressions', 'ctr', 'position'],
    title: 'GSCQueryRow',
    description: 'Schema for a single query row in GSC API responses.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IntersectDomainSchema = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain'
        },
        backlinks_count: {
            type: 'integer',
            title: 'Backlinks Count'
        },
        dofollow_count: {
            type: 'integer',
            title: 'Dofollow Count'
        },
        nofollow_count: {
            type: 'integer',
            title: 'Nofollow Count'
        }
    },
    type: 'object',
    required: ['domain', 'backlinks_count', 'dofollow_count', 'nofollow_count'],
    title: 'IntersectDomain',
    description: 'API response row for backlink intersection analysis.'
} as const;

export const IntersectResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/IntersectDomain'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'IntersectResponse',
    description: 'API response for backlink intersection endpoint.'
} as const;

export const IssueSeveritySchema = {
    type: 'string',
    enum: ['critical', 'high', 'medium', 'low'],
    title: 'IssueSeverity'
} as const;

export const IssueTypeSchema = {
    type: 'string',
    enum: ['server_error_5xx', 'redirect_loop', 'redirect_chain', 'broken_internal_link', 'client_error_4xx', 'missing_title', 'duplicate_title', 'missing_meta_description', 'title_too_long', 'title_too_short', 'meta_desc_too_long', 'meta_desc_too_short', 'missing_h1', 'multiple_h1', 'missing_canonical', 'canonical_mismatch', 'non_https', 'thin_content', 'orphan_page'],
    title: 'IssueType'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const JobStatusSchema = {
    type: 'string',
    enum: ['queued', 'running', 'completed', 'failed', 'cancelled'],
    title: 'JobStatus',
    description: 'Job execution status.'
} as const;

export const JobStatusResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        job_type: {
            type: 'string',
            title: 'Job Type'
        },
        status: {
            '$ref': '#/components/schemas/JobStatus'
        },
        progress_pct: {
            type: 'integer',
            title: 'Progress Pct'
        },
        progress_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress Message'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: ['id', 'job_type', 'status', 'progress_pct', 'progress_message', 'started_at', 'finished_at', 'error_message'],
    title: 'JobStatusResponse',
    description: 'Response model for job status.'
} as const;

export const JobsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/JobStatusResponse'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'JobsPublic',
    description: 'Response model for listing multiple jobs.'
} as const;

export const KeywordTargetCreateSchema = {
    properties: {
        keyword: {
            type: 'string',
            maxLength: 500,
            title: 'Keyword'
        },
        locale: {
            type: 'string',
            maxLength: 10,
            title: 'Locale'
        },
        device: {
            '$ref': '#/components/schemas/DeviceType',
            default: 'desktop'
        },
        search_engine: {
            '$ref': '#/components/schemas/SearchEngine',
            default: 'google'
        },
        provider_key: {
            type: 'string',
            maxLength: 50,
            title: 'Provider Key',
            default: 'serpapi'
        },
        refresh_frequency_hours: {
            type: 'integer',
            maximum: 168,
            minimum: 1,
            title: 'Refresh Frequency Hours',
            default: 24
        }
    },
    type: 'object',
    required: ['keyword', 'locale'],
    title: 'KeywordTargetCreate',
    description: 'Schema for creating a new keyword target.'
} as const;

export const KeywordTargetPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        keyword: {
            type: 'string',
            title: 'Keyword'
        },
        locale: {
            type: 'string',
            title: 'Locale'
        },
        device: {
            '$ref': '#/components/schemas/DeviceType'
        },
        search_engine: {
            '$ref': '#/components/schemas/SearchEngine'
        },
        provider_key: {
            type: 'string',
            title: 'Provider Key'
        },
        refresh_frequency_hours: {
            type: 'integer',
            title: 'Refresh Frequency Hours'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        latest_position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Position'
        },
        position_change: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Change'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        last_refresh_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Refresh At'
        },
        last_refresh_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Refresh Status'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'keyword', 'locale', 'device', 'search_engine', 'provider_key', 'refresh_frequency_hours', 'is_active', 'latest_position', 'position_change', 'created_at', 'updated_at', 'last_refresh_at', 'last_refresh_status'],
    title: 'KeywordTargetPublic',
    description: 'Public schema for returning keyword target data.'
} as const;

export const KeywordTargetsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/KeywordTargetPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'KeywordTargetsPublic',
    description: 'Schema for returning multiple keyword targets.'
} as const;

export const KeywordsResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PaidKeywordRow'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'KeywordsResponse',
    description: 'API response for keywords endpoint.'
} as const;

export const LinkAdsAccountRequestSchema = {
    properties: {
        customer_id: {
            type: 'string',
            title: 'Customer Id'
        }
    },
    type: 'object',
    required: ['customer_id'],
    title: 'LinkAdsAccountRequest',
    description: 'Request model for linking a Google Ads account.'
} as const;

export const LinkPropertyRequestSchema = {
    properties: {
        site_url: {
            type: 'string',
            title: 'Site Url'
        }
    },
    type: 'object',
    required: ['site_url'],
    title: 'LinkPropertyRequest',
    description: 'Request model for linking a GSC property.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OpportunitiesResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OpportunityRow'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OpportunitiesResponse',
    description: 'Schema for returning multiple opportunities.'
} as const;

export const OpportunityRowSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        impressions: {
            type: 'integer',
            title: 'Impressions'
        },
        clicks: {
            type: 'integer',
            title: 'Clicks'
        },
        ctr: {
            type: 'number',
            title: 'Ctr'
        },
        position: {
            type: 'number',
            title: 'Position'
        },
        opportunity_type: {
            type: 'string',
            title: 'Opportunity Type'
        },
        potential_clicks: {
            type: 'integer',
            title: 'Potential Clicks'
        }
    },
    type: 'object',
    required: ['query', 'impressions', 'clicks', 'ctr', 'position', 'opportunity_type', 'potential_clicks'],
    title: 'OpportunityRow',
    description: 'Schema for SEO opportunity data.'
} as const;

export const OverlapDomainSchema = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain'
        },
        links_to_a: {
            type: 'integer',
            title: 'Links To A'
        },
        links_to_b: {
            type: 'integer',
            title: 'Links To B'
        },
        total_backlinks: {
            type: 'integer',
            title: 'Total Backlinks'
        }
    },
    type: 'object',
    required: ['domain', 'links_to_a', 'links_to_b', 'total_backlinks'],
    title: 'OverlapDomain',
    description: 'API response row for backlink overlap analysis.'
} as const;

export const OverlapRowSchema = {
    properties: {
        keyword: {
            type: 'string',
            title: 'Keyword'
        },
        organic_position: {
            type: 'number',
            title: 'Organic Position'
        },
        paid_position: {
            type: 'number',
            title: 'Paid Position'
        },
        organic_clicks: {
            type: 'integer',
            title: 'Organic Clicks'
        },
        paid_clicks: {
            type: 'integer',
            title: 'Paid Clicks'
        },
        total_clicks: {
            type: 'integer',
            title: 'Total Clicks'
        },
        paid_cost_micros: {
            type: 'integer',
            title: 'Paid Cost Micros'
        },
        opportunity_score: {
            type: 'number',
            title: 'Opportunity Score'
        },
        overlap_type: {
            type: 'string',
            title: 'Overlap Type'
        }
    },
    type: 'object',
    required: ['keyword', 'organic_position', 'paid_position', 'organic_clicks', 'paid_clicks', 'total_clicks', 'paid_cost_micros', 'opportunity_score', 'overlap_type'],
    title: 'OverlapRow',
    description: 'API response row for organic/paid keyword overlap analysis.'
} as const;

export const OverlapSummarySchema = {
    properties: {
        total_keywords: {
            type: 'integer',
            title: 'Total Keywords'
        },
        overlap_count: {
            type: 'integer',
            title: 'Overlap Count'
        },
        paid_only_count: {
            type: 'integer',
            title: 'Paid Only Count'
        },
        organic_only_count: {
            type: 'integer',
            title: 'Organic Only Count'
        }
    },
    type: 'object',
    required: ['total_keywords', 'overlap_count', 'paid_only_count', 'organic_only_count'],
    title: 'OverlapSummary',
    description: 'Summary statistics for keyword overlap analysis.'
} as const;

export const PaidKeywordRowSchema = {
    properties: {
        keyword_text: {
            type: 'string',
            title: 'Keyword Text'
        },
        match_type: {
            type: 'string',
            title: 'Match Type'
        },
        impressions: {
            type: 'integer',
            title: 'Impressions'
        },
        clicks: {
            type: 'integer',
            title: 'Clicks'
        },
        cost_micros: {
            type: 'integer',
            title: 'Cost Micros'
        },
        conversions: {
            type: 'number',
            title: 'Conversions'
        },
        average_cpc_micros: {
            type: 'integer',
            title: 'Average Cpc Micros'
        },
        quality_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quality Score'
        }
    },
    type: 'object',
    required: ['keyword_text', 'match_type', 'impressions', 'clicks', 'cost_micros', 'conversions', 'average_cpc_micros', 'quality_score'],
    title: 'PaidKeywordRow',
    description: 'API response row for paid keyword performance.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        seed_url: {
            type: 'string',
            maxLength: 2048,
            title: 'Seed Url'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        settings: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectSettings'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['name', 'seed_url'],
    title: 'ProjectCreate',
    description: 'Schema for creating a new project.'
} as const;

export const ProjectPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        seed_url: {
            type: 'string',
            maxLength: 2048,
            title: 'Seed Url'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        settings: {
            additionalProperties: true,
            type: 'object',
            title: 'Settings'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        last_audit_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Audit At'
        },
        last_gsc_sync_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Gsc Sync At'
        },
        last_serp_refresh_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Serp Refresh At'
        },
        last_links_snapshot_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Links Snapshot At'
        },
        last_ppc_sync_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Ppc Sync At'
        }
    },
    type: 'object',
    required: ['name', 'seed_url', 'id', 'created_by_id', 'settings', 'created_at', 'updated_at', 'last_audit_at', 'last_gsc_sync_at', 'last_serp_refresh_at', 'last_links_snapshot_at', 'last_ppc_sync_at'],
    title: 'ProjectPublic',
    description: 'Public schema for returning project data.'
} as const;

export const ProjectSettingsSchema = {
    properties: {
        max_pages: {
            type: 'integer',
            title: 'Max Pages',
            default: 1000
        },
        max_depth: {
            type: 'integer',
            title: 'Max Depth',
            default: 10
        },
        crawl_concurrency: {
            type: 'integer',
            title: 'Crawl Concurrency',
            default: 5
        },
        user_agent: {
            type: 'string',
            title: 'User Agent',
            default: 'SEOPlatformBot/1.0'
        },
        respect_robots_txt: {
            type: 'boolean',
            title: 'Respect Robots Txt',
            default: true
        },
        include_subdomains: {
            type: 'boolean',
            title: 'Include Subdomains',
            default: false
        },
        strip_query_params: {
            type: 'boolean',
            title: 'Strip Query Params',
            default: false
        },
        include_patterns: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Include Patterns',
            default: []
        },
        exclude_patterns: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Exclude Patterns',
            default: []
        },
        enable_js_rendering: {
            type: 'boolean',
            title: 'Enable Js Rendering',
            default: false
        },
        js_render_mode: {
            type: 'string',
            title: 'Js Render Mode',
            default: 'hybrid'
        },
        max_render_pages: {
            type: 'integer',
            title: 'Max Render Pages',
            default: 100
        },
        render_timeout_ms: {
            type: 'integer',
            title: 'Render Timeout Ms',
            default: 30000
        },
        audit_frequency: {
            type: 'string',
            title: 'Audit Frequency',
            default: 'weekly'
        },
        gsc_sync_frequency: {
            type: 'string',
            title: 'Gsc Sync Frequency',
            default: 'daily'
        },
        serp_refresh_frequency: {
            type: 'string',
            title: 'Serp Refresh Frequency',
            default: 'daily'
        },
        keep_audit_runs: {
            type: 'integer',
            title: 'Keep Audit Runs',
            default: 10
        },
        keep_serp_days: {
            type: 'integer',
            title: 'Keep Serp Days',
            default: 90
        }
    },
    type: 'object',
    title: 'ProjectSettings',
    description: 'Project configuration settings stored as JSON.'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        seed_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seed Url'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        settings: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectSettings'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ProjectUpdate',
    description: 'Schema for updating an existing project.'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic',
    description: 'Schema for returning multiple projects.'
} as const;

export const RankHistoryResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RankObservationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RankHistoryResponse',
    description: 'Schema for returning rank history.'
} as const;

export const RankObservationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        keyword_target_id: {
            type: 'string',
            format: 'uuid',
            title: 'Keyword Target Id'
        },
        observed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Observed At'
        },
        rank: {
            type: 'integer',
            title: 'Rank'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        domain: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Domain'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        snippet: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Snippet'
        },
        status: {
            '$ref': '#/components/schemas/RefreshStatus'
        }
    },
    type: 'object',
    required: ['id', 'keyword_target_id', 'observed_at', 'rank', 'url', 'domain', 'title', 'snippet', 'status'],
    title: 'RankObservationPublic',
    description: 'Public schema for returning rank observation data.'
} as const;

export const RefDomainRowSchema = {
    properties: {
        ref_domain: {
            type: 'string',
            title: 'Ref Domain'
        },
        backlinks: {
            type: 'integer',
            title: 'Backlinks'
        },
        dofollow: {
            type: 'integer',
            title: 'Dofollow'
        },
        nofollow: {
            type: 'integer',
            title: 'Nofollow'
        },
        first_seen: {
            type: 'string',
            format: 'date-time',
            title: 'First Seen'
        },
        last_seen: {
            type: 'string',
            format: 'date-time',
            title: 'Last Seen'
        }
    },
    type: 'object',
    required: ['ref_domain', 'backlinks', 'dofollow', 'nofollow', 'first_seen', 'last_seen'],
    title: 'RefDomainRow',
    description: 'API response row for referring domains list.'
} as const;

export const RefDomainsResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RefDomainRow'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'RefDomainsResponse',
    description: 'API response for referring domains endpoint.'
} as const;

export const RefreshStatusSchema = {
    type: 'string',
    enum: ['pending', 'success', 'failed', 'rate_limited'],
    title: 'RefreshStatus',
    description: 'Status of SERP refresh operation.'
} as const;

export const SearchEngineSchema = {
    type: 'string',
    enum: ['google', 'bing'],
    title: 'SearchEngine',
    description: 'Supported search engines.'
} as const;

export const SerpResultPublicSchema = {
    properties: {
        position: {
            type: 'integer',
            title: 'Position'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        domain: {
            type: 'string',
            title: 'Domain'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        snippet: {
            type: 'string',
            title: 'Snippet'
        },
        displayed_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Displayed Url'
        }
    },
    type: 'object',
    required: ['position', 'url', 'domain', 'title', 'snippet'],
    title: 'SerpResultPublic',
    description: 'Schema for a single SERP result.'
} as const;

export const SerpSnapshotPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        keyword_target_id: {
            type: 'string',
            format: 'uuid',
            title: 'Keyword Target Id'
        },
        captured_at: {
            type: 'string',
            format: 'date-time',
            title: 'Captured At'
        },
        results: {
            items: {
                '$ref': '#/components/schemas/SerpResultPublic'
            },
            type: 'array',
            title: 'Results'
        },
        total_results: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Results'
        }
    },
    type: 'object',
    required: ['id', 'keyword_target_id', 'captured_at', 'results', 'total_results'],
    title: 'SerpSnapshotPublic',
    description: 'Public schema for returning SERP snapshot data.'
} as const;

export const SerpSnapshotsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SerpSnapshotPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SerpSnapshotsPublic',
    description: 'Schema for returning multiple SERP snapshots.'
} as const;

export const TaskResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        task_id: {
            type: 'string',
            title: 'Task Id'
        }
    },
    type: 'object',
    required: ['message', 'task_id'],
    title: 'TaskResponse',
    description: 'Response model for async task triggers.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TrafficPanelResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TrafficPanelRow'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'TrafficPanelResponse',
    description: 'API response for traffic panel endpoint.'
} as const;

export const TrafficPanelRowSchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        sessions: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sessions'
        },
        users: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Users'
        },
        pageviews: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pageviews'
        },
        bounce_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bounce Rate'
        },
        avg_session_duration: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Session Duration'
        },
        organic_clicks: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Organic Clicks'
        },
        paid_clicks: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid Clicks'
        }
    },
    type: 'object',
    required: ['date', 'sessions', 'users', 'pageviews', 'bounce_rate', 'avg_session_duration', 'organic_clicks', 'paid_clicks'],
    title: 'TrafficPanelRow',
    description: 'API response row for traffic panel (time series data).'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const app__models__ads__OverlapResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OverlapRow'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        summary: {
            '$ref': '#/components/schemas/OverlapSummary'
        }
    },
    type: 'object',
    required: ['data', 'total', 'summary'],
    title: 'OverlapResponse',
    description: 'API response for keyword overlap endpoint.'
} as const;

export const app__models__links__OverlapResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OverlapDomain'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'OverlapResponse',
    description: 'API response for backlink overlap endpoint.'
} as const;