// This file is auto-generated by @hey-api/openapi-ts

/**
 * Public response model for ads account.
 */
export type AdsAccountPublic = {
    id: string;
    project_id: string;
    customer_id: string;
    descriptive_name: (string | null);
    currency_code: string;
    linked_at: string;
    last_sync_at: (string | null);
    sync_status: string;
};

/**
 * API response row for anchor texts list.
 */
export type AnchorRow = {
    anchor_text: string;
    backlinks: number;
    ref_domains: number;
};

/**
 * API response for anchor texts endpoint.
 */
export type AnchorsResponse = {
    data: Array<AnchorRow>;
    total: number;
};

/**
 * API response for keyword overlap endpoint.
 */
export type app__models__ads__OverlapResponse = {
    data: Array<OverlapRow>;
    total: number;
    summary: OverlapSummary;
};

/**
 * API response for backlink overlap endpoint.
 */
export type app__models__links__OverlapResponse = {
    data: Array<OverlapDomain>;
    total: number;
};

export type AuditIssuePublic = {
    id: string;
    audit_run_id: string;
    page_url: string;
    issue_type: IssueType;
    severity: IssueSeverity;
    details: {
        [key: string]: unknown;
    };
    first_seen_run_id: (string | null);
    is_new: boolean;
};

export type AuditIssuesPublic = {
    data: Array<AuditIssuePublic>;
    count: number;
};

export type AuditRunPublic = {
    id: string;
    project_id: string;
    status: AuditStatus;
    config: {
        [key: string]: unknown;
    };
    stats: ({
    [key: string]: unknown;
} | null);
    progress_pct: number;
    progress_message: (string | null);
    started_at: (string | null);
    finished_at: (string | null);
    error_message: (string | null);
    created_at: string;
};

export type AuditRunsPublic = {
    data: Array<AuditRunPublic>;
    count: number;
};

export type AuditStatus = 'queued' | 'crawling' | 'rendering' | 'analyzing' | 'diffing' | 'completed' | 'failed';

/**
 * Response model for backfill task.
 */
export type BackfillTaskResponse = {
    message: string;
    task_id: string;
    days: number;
};

/**
 * API response row for backlinks list.
 */
export type BacklinkRow = {
    source_url: string;
    target_url: string;
    source_domain: string;
    anchor_text: (string | null);
    is_nofollow: boolean;
    first_seen: string;
    last_seen: string;
};

/**
 * API response for backlinks endpoint.
 */
export type BacklinksResponse = {
    data: Array<BacklinkRow>;
    total: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * API response row for campaign performance.
 */
export type CampaignRow = {
    campaign_id: string;
    campaign_name: string;
    campaign_status: string;
    impressions: number;
    clicks: number;
    cost_micros: number;
    conversions: number;
    conversion_value: number;
};

/**
 * API response for campaigns endpoint.
 */
export type CampaignsResponse = {
    data: Array<CampaignRow>;
    total: number;
};

/**
 * Public schema for cluster details with member queries.
 */
export type ClusterDetailPublic = {
    id: string;
    project_id: string;
    label: string;
    algorithm: string;
    created_at: string;
    total_clicks: number;
    total_impressions: number;
    avg_position: number;
    query_count: number;
    members: Array<ClusterMemberPublic>;
};

/**
 * Public schema for a cluster member query with metrics.
 */
export type ClusterMemberPublic = {
    id: string;
    cluster_id: string;
    query: string;
    weight: number;
    clicks: number;
    impressions: number;
    ctr: number;
    position: number;
};

/**
 * Public schema for returning keyword cluster data.
 */
export type ClusterPublic = {
    id: string;
    project_id: string;
    label: string;
    algorithm: string;
    created_at: string;
    total_clicks: number;
    total_impressions: number;
    avg_position: number;
    query_count: number;
};

/**
 * Response model for keyword clusters.
 */
export type ClustersResponse = {
    data: Array<ClusterPublic>;
    count: number;
};

export type CrawledPagePublic = {
    id: string;
    audit_run_id: string;
    url: string;
    final_url: string;
    depth: number;
    status_code: number;
    content_type: (string | null);
    response_time_ms: (number | null);
    redirect_chain: (Array<{
    [key: string]: unknown;
}> | null);
    title: (string | null);
    meta_description: (string | null);
    canonical: (string | null);
    h1_count: (number | null);
    first_h1: (string | null);
    word_count: (number | null);
    meta_robots: (string | null);
    is_rendered: boolean;
    rendered_at: (string | null);
    rendered_title: (string | null);
    rendered_meta_description: (string | null);
    rendered_h1_count: (number | null);
    rendered_word_count: (number | null);
    content_hash: (string | null);
    crawled_at: string;
};

export type CrawledPagesPublic = {
    data: Array<CrawledPagePublic>;
    count: number;
};

/**
 * Request model for CSV import.
 */
export type CSVImportRequest = {
    csv_data: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Response model for CSV import.
 */
export type CSVImportResponse = {
    imported: number;
};

/**
 * Device types for SERP tracking.
 */
export type DeviceType = 'desktop' | 'mobile' | 'tablet';

/**
 * Schema for a single page row in GSC API responses.
 */
export type GSCPageRow = {
    page: string;
    clicks: number;
    impressions: number;
    ctr: number;
    position: number;
};

/**
 * Schema for returning multiple GSC pages.
 */
export type GSCPagesResponse = {
    data: Array<GSCPageRow>;
    count: number;
};

/**
 * Public schema for returning GSC property data.
 */
export type GSCPropertyPublic = {
    id: string;
    project_id: string;
    site_url: string;
    permission_level: (string | null);
    verified: boolean;
    linked_at: string;
    last_sync_at: (string | null);
    sync_status: string;
    sync_error: (string | null);
    search_type: string;
};

/**
 * Schema for returning multiple GSC queries.
 */
export type GSCQueriesResponse = {
    data: Array<GSCQueryRow>;
    count: number;
};

/**
 * Schema for a single query row in GSC API responses.
 */
export type GSCQueryRow = {
    query: string;
    clicks: number;
    impressions: number;
    ctr: number;
    position: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * API response row for backlink intersection analysis.
 */
export type IntersectDomain = {
    domain: string;
    backlinks_count: number;
    dofollow_count: number;
    nofollow_count: number;
};

/**
 * API response for backlink intersection endpoint.
 */
export type IntersectResponse = {
    data: Array<IntersectDomain>;
    total: number;
};

export type IssueSeverity = 'critical' | 'high' | 'medium' | 'low';

export type IssueType = 'server_error_5xx' | 'redirect_loop' | 'redirect_chain' | 'broken_internal_link' | 'client_error_4xx' | 'missing_title' | 'duplicate_title' | 'missing_meta_description' | 'title_too_long' | 'title_too_short' | 'meta_desc_too_long' | 'meta_desc_too_short' | 'missing_h1' | 'multiple_h1' | 'missing_canonical' | 'canonical_mismatch' | 'non_https' | 'thin_content' | 'orphan_page';

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Response model for listing multiple jobs.
 */
export type JobsPublic = {
    data: Array<JobStatusResponse>;
    count: number;
};

/**
 * Job execution status.
 */
export type JobStatus = 'queued' | 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * Response model for job status.
 */
export type JobStatusResponse = {
    id: string;
    job_type: string;
    status: JobStatus;
    progress_pct: number;
    progress_message: (string | null);
    started_at: (string | null);
    finished_at: (string | null);
    error_message: (string | null);
};

/**
 * API response for keywords endpoint.
 */
export type KeywordsResponse = {
    data: Array<PaidKeywordRow>;
    total: number;
};

/**
 * Schema for creating a new keyword target.
 */
export type KeywordTargetCreate = {
    keyword: string;
    locale: string;
    device?: DeviceType;
    search_engine?: SearchEngine;
    provider_key?: string;
    refresh_frequency_hours?: number;
};

/**
 * Public schema for returning keyword target data.
 */
export type KeywordTargetPublic = {
    id: string;
    project_id: string;
    keyword: string;
    locale: string;
    device: DeviceType;
    search_engine: SearchEngine;
    provider_key: string;
    refresh_frequency_hours: number;
    is_active: boolean;
    latest_position: (number | null);
    position_change: (number | null);
    created_at: string;
    updated_at: string;
    last_refresh_at: (string | null);
    last_refresh_status: (string | null);
};

/**
 * Schema for returning multiple keyword targets.
 */
export type KeywordTargetsPublic = {
    data: Array<KeywordTargetPublic>;
    count: number;
};

/**
 * Request model for linking a Google Ads account.
 */
export type LinkAdsAccountRequest = {
    customer_id: string;
};

/**
 * Request model for linking a GSC property.
 */
export type LinkPropertyRequest = {
    site_url: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Schema for returning multiple opportunities.
 */
export type OpportunitiesResponse = {
    data: Array<OpportunityRow>;
    count: number;
};

/**
 * Schema for SEO opportunity data.
 */
export type OpportunityRow = {
    query: string;
    impressions: number;
    clicks: number;
    ctr: number;
    position: number;
    opportunity_type: string;
    potential_clicks: number;
};

/**
 * API response row for backlink overlap analysis.
 */
export type OverlapDomain = {
    domain: string;
    links_to_a: number;
    links_to_b: number;
    total_backlinks: number;
};

/**
 * API response row for organic/paid keyword overlap analysis.
 */
export type OverlapRow = {
    keyword: string;
    organic_position: number;
    paid_position: number;
    organic_clicks: number;
    paid_clicks: number;
    total_clicks: number;
    paid_cost_micros: number;
    opportunity_score: number;
    overlap_type: string;
};

/**
 * Summary statistics for keyword overlap analysis.
 */
export type OverlapSummary = {
    total_keywords: number;
    overlap_count: number;
    paid_only_count: number;
    organic_only_count: number;
};

/**
 * API response row for paid keyword performance.
 */
export type PaidKeywordRow = {
    keyword_text: string;
    match_type: string;
    impressions: number;
    clicks: number;
    cost_micros: number;
    conversions: number;
    average_cpc_micros: number;
    quality_score: (number | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Schema for creating a new project.
 */
export type ProjectCreate = {
    name: string;
    seed_url: string;
    description?: (string | null);
    settings?: (ProjectSettings | null);
};

/**
 * Public schema for returning project data.
 */
export type ProjectPublic = {
    name: string;
    seed_url: string;
    description?: (string | null);
    id: string;
    created_by_id: string;
    settings: {
        [key: string]: unknown;
    };
    created_at: string;
    updated_at: string;
    last_audit_at: (string | null);
    last_gsc_sync_at: (string | null);
    last_serp_refresh_at: (string | null);
    last_links_snapshot_at: (string | null);
    last_ppc_sync_at: (string | null);
};

/**
 * Project configuration settings stored as JSON.
 */
export type ProjectSettings = {
    max_pages?: number;
    max_depth?: number;
    crawl_concurrency?: number;
    user_agent?: string;
    respect_robots_txt?: boolean;
    include_subdomains?: boolean;
    strip_query_params?: boolean;
    include_patterns?: Array<(string)>;
    exclude_patterns?: Array<(string)>;
    enable_js_rendering?: boolean;
    js_render_mode?: string;
    max_render_pages?: number;
    render_timeout_ms?: number;
    audit_frequency?: string;
    gsc_sync_frequency?: string;
    serp_refresh_frequency?: string;
    keep_audit_runs?: number;
    keep_serp_days?: number;
};

/**
 * Schema for returning multiple projects.
 */
export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

/**
 * Schema for updating an existing project.
 */
export type ProjectUpdate = {
    name?: (string | null);
    seed_url?: (string | null);
    description?: (string | null);
    settings?: (ProjectSettings | null);
};

/**
 * Schema for returning rank history.
 */
export type RankHistoryResponse = {
    data: Array<RankObservationPublic>;
    count: number;
};

/**
 * Public schema for returning rank observation data.
 */
export type RankObservationPublic = {
    id: string;
    keyword_target_id: string;
    observed_at: string;
    rank: number;
    url: (string | null);
    domain: (string | null);
    title: (string | null);
    snippet: (string | null);
    status: RefreshStatus;
};

/**
 * API response row for referring domains list.
 */
export type RefDomainRow = {
    ref_domain: string;
    backlinks: number;
    dofollow: number;
    nofollow: number;
    first_seen: string;
    last_seen: string;
};

/**
 * API response for referring domains endpoint.
 */
export type RefDomainsResponse = {
    data: Array<RefDomainRow>;
    total: number;
};

/**
 * Status of SERP refresh operation.
 */
export type RefreshStatus = 'pending' | 'success' | 'failed' | 'rate_limited';

/**
 * Supported search engines.
 */
export type SearchEngine = 'google' | 'bing';

/**
 * Schema for a single SERP result.
 */
export type SerpResultPublic = {
    position: number;
    url: string;
    domain: string;
    title: string;
    snippet: string;
    displayed_url?: (string | null);
};

/**
 * Public schema for returning SERP snapshot data.
 */
export type SerpSnapshotPublic = {
    id: string;
    keyword_target_id: string;
    captured_at: string;
    results: Array<SerpResultPublic>;
    total_results: (number | null);
};

/**
 * Schema for returning multiple SERP snapshots.
 */
export type SerpSnapshotsPublic = {
    data: Array<SerpSnapshotPublic>;
    count: number;
};

/**
 * Response model for async task triggers.
 */
export type TaskResponse = {
    message: string;
    task_id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * API response for traffic panel endpoint.
 */
export type TrafficPanelResponse = {
    data: Array<TrafficPanelRow>;
    total: number;
};

/**
 * API response row for traffic panel (time series data).
 */
export type TrafficPanelRow = {
    date: string;
    sessions: (number | null);
    users: (number | null);
    pageviews: (number | null);
    bounce_rate: (number | null);
    avg_session_duration: (number | null);
    organic_clicks: (number | null);
    paid_clicks: (number | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AdsListAvailableAccountsData = {
    projectId: string;
};

export type AdsListAvailableAccountsResponse = (Array<{
    [key: string]: unknown;
}>);

export type AdsLinkAdsAccountData = {
    projectId: string;
    requestBody: LinkAdsAccountRequest;
};

export type AdsLinkAdsAccountResponse = (AdsAccountPublic);

export type AdsTriggerSyncData = {
    projectId: string;
};

export type AdsTriggerSyncResponse = (TaskResponse);

export type AdsGetCampaignsData = {
    periodDays?: number;
    projectId: string;
};

export type AdsGetCampaignsResponse = (CampaignsResponse);

export type AdsGetKeywordsData = {
    limit?: number;
    periodDays?: number;
    projectId: string;
    search?: (string | null);
    skip?: number;
};

export type AdsGetKeywordsResponse = (KeywordsResponse);

export type AdsGetSeoOverlapData = {
    overlapType?: (string | null);
    periodDays?: number;
    projectId: string;
};

export type AdsGetSeoOverlapResponse = (app__models__ads__OverlapResponse);

export type AuditsStartAuditData = {
    projectId: string;
};

export type AuditsStartAuditResponse = (AuditRunPublic);

export type AuditsListAuditsData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type AuditsListAuditsResponse = (AuditRunsPublic);

export type AuditsGetAuditData = {
    auditId: string;
    projectId: string;
};

export type AuditsGetAuditResponse = (AuditRunPublic);

export type AuditsGetAuditIssuesData = {
    auditId: string;
    isNew?: (boolean | null);
    issueType?: (IssueType | null);
    limit?: number;
    projectId: string;
    severity?: (IssueSeverity | null);
    skip?: number;
};

export type AuditsGetAuditIssuesResponse = (AuditIssuesPublic);

export type AuditsGetAuditPagesData = {
    auditId: string;
    isRendered?: (boolean | null);
    limit?: number;
    projectId: string;
    skip?: number;
    statusCode?: (number | null);
};

export type AuditsGetAuditPagesResponse = (CrawledPagesPublic);

export type AuditsGetPageDetailData = {
    auditId: string;
    pageId: string;
    projectId: string;
};

export type AuditsGetPageDetailResponse = (CrawledPagePublic);

export type AuditsExportIssuesCsvData = {
    auditId: string;
    isNew?: (boolean | null);
    issueType?: (IssueType | null);
    projectId: string;
    severity?: (IssueSeverity | null);
};

export type AuditsExportIssuesCsvResponse = (unknown);

export type GscListAvailablePropertiesData = {
    projectId: string;
};

export type GscListAvailablePropertiesResponse = (Array<{
    [key: string]: unknown;
}>);

export type GscLinkPropertyData = {
    projectId: string;
    requestBody: LinkPropertyRequest;
};

export type GscLinkPropertyResponse = (GSCPropertyPublic);

export type GscUnlinkPropertyData = {
    projectId: string;
};

export type GscUnlinkPropertyResponse = ({
    [key: string]: (string);
});

export type GscTriggerSyncData = {
    projectId: string;
};

export type GscTriggerSyncResponse = (TaskResponse);

export type GscTriggerBackfillData = {
    days?: number;
    projectId: string;
};

export type GscTriggerBackfillResponse = (BackfillTaskResponse);

export type GscGetQueriesData = {
    limit?: number;
    periodDays?: number;
    projectId: string;
    search?: (string | null);
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type GscGetQueriesResponse = (GSCQueriesResponse);

export type GscGetPagesData = {
    limit?: number;
    periodDays?: number;
    projectId: string;
    search?: (string | null);
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type GscGetPagesResponse = (GSCPagesResponse);

export type GscGetOpportunitiesData = {
    limit?: number;
    opportunityType?: (string | null);
    projectId: string;
    skip?: number;
};

export type GscGetOpportunitiesResponse = (OpportunitiesResponse);

export type GscGetClustersData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type GscGetClustersResponse = (ClustersResponse);

export type GscGenerateClustersData = {
    projectId: string;
};

export type GscGenerateClustersResponse = (TaskResponse);

export type GscGetClusterDetailData = {
    clusterId: string;
    periodDays?: number;
    projectId: string;
};

export type GscGetClusterDetailResponse = (ClusterDetailPublic);

export type IntegrationsStartGoogleOauthData = {
    service: string;
};

export type IntegrationsStartGoogleOauthResponse = ({
    [key: string]: (string);
});

export type IntegrationsGoogleOauthCallbackData = {
    code: string;
    state: string;
};

export type IntegrationsGoogleOauthCallbackResponse = (unknown);

export type IntegrationsGetGoogleIntegrationStatusResponse = ({
    [key: string]: (boolean | string | null);
});

export type IntegrationsDisconnectGoogleIntegrationData = {
    service: string;
};

export type IntegrationsDisconnectGoogleIntegrationResponse = ({
    [key: string]: (string);
});

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JobsGetJobStatusData = {
    jobId: string;
};

export type JobsGetJobStatusResponse = (JobStatusResponse);

export type JobsListProjectJobsData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type JobsListProjectJobsResponse = (JobsPublic);

export type JobsCancelJobData = {
    jobId: string;
};

export type JobsCancelJobResponse = (Message);

export type LinksGetRefdomainsData = {
    domain: string;
    limit?: number;
    skip?: number;
};

export type LinksGetRefdomainsResponse = (RefDomainsResponse);

export type LinksGetBacklinksData = {
    domain: string;
    limit?: number;
    refDomain?: (string | null);
    skip?: number;
};

export type LinksGetBacklinksResponse = (BacklinksResponse);

export type LinksGetAnchorsData = {
    domain: string;
    limit?: number;
    skip?: number;
};

export type LinksGetAnchorsResponse = (AnchorsResponse);

export type LinksGetOverlapData = {
    /**
     * Comma-separated list of competitor domains
     */
    competitors: string;
    domain: string;
};

export type LinksGetOverlapResponse = (app__models__links__OverlapResponse);

export type LinksGetIntersectData = {
    /**
     * Comma-separated list of competitor domains
     */
    competitors: string;
    domain: string;
};

export type LinksGetIntersectResponse = (IntersectResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectData = {
    id: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    id: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    id: string;
};

export type ProjectsDeleteProjectResponse = (Message);

export type SerpListProvidersData = {
    projectId: string;
};

export type SerpListProvidersResponse = (Array<{
    [key: string]: unknown;
}>);

export type SerpAddKeywordData = {
    projectId: string;
    requestBody: KeywordTargetCreate;
};

export type SerpAddKeywordResponse = (KeywordTargetPublic);

export type SerpListKeywordsData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type SerpListKeywordsResponse = (KeywordTargetsPublic);

export type SerpDeleteKeywordData = {
    keywordId: string;
    projectId: string;
};

export type SerpDeleteKeywordResponse = (Message);

export type SerpGetKeywordData = {
    keywordId: string;
    projectId: string;
};

export type SerpGetKeywordResponse = (KeywordTargetPublic);

export type SerpRefreshKeywordManualData = {
    keywordId: string;
    projectId: string;
};

export type SerpRefreshKeywordManualResponse = (Message);

export type SerpRefreshAllData = {
    projectId: string;
};

export type SerpRefreshAllResponse = (Message);

export type SerpGetRankHistoryData = {
    days?: number;
    keywordId: string;
    projectId: string;
};

export type SerpGetRankHistoryResponse = (RankHistoryResponse);

export type SerpGetLatestSnapshotData = {
    keywordId: string;
    projectId: string;
};

export type SerpGetLatestSnapshotResponse = (SerpSnapshotPublic);

export type SerpGetSerpSnapshotData = {
    keywordId: string;
    projectId: string;
    snapshotId: string;
};

export type SerpGetSerpSnapshotResponse = (SerpSnapshotPublic);

export type SerpListKeywordSnapshotsData = {
    keywordId: string;
    limit?: number;
    projectId: string;
    skip?: number;
};

export type SerpListKeywordSnapshotsResponse = (SerpSnapshotsPublic);

export type TrafficGetTrafficPanelData = {
    periodDays?: number;
    projectId: string;
};

export type TrafficGetTrafficPanelResponse = (TrafficPanelResponse);

export type TrafficImportCsvData = {
    projectId: string;
    requestBody: CSVImportRequest;
};

export type TrafficImportCsvResponse = (CSVImportResponse);

export type TrafficGetAvailableSourcesData = {
    projectId: string;
};

export type TrafficGetAvailableSourcesResponse = (Array<(string)>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);